name = "lightweight-ims"
main = "worker/index.ts"
compatibility_date = "2026-08-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SYNC_KV"
id = "22486bf0747a46939cbcb3f75f3b1bfa"
preview_id = "22486bf0747a46939cbcb3f75f3b1bfa"
